version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inerview-app:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0 -XX:+UseZGC
    restart: unless-stopped
